[package]
name = "tidal-repl"
version = "0.1.12"
edition = "2024"

[dependencies]
tidal-parser = { path = "../tidal-parser" }
tidal-runtime = { path = "../tidal-runtime" }
tidal-errors = { path = "../tidal-errors" }
tidal-lexer = { path = "../tidal-lexer" }
