[package]
name = "tidal-cli"
version = "0.1.11"
edition = "2024"

[dependencies]
tidal-parser = { path = "../tidal-parser" }
tidal-runtime = { path = "../tidal-runtime" }
tidal-errors = { path = "../tidal-errors" }
tidal-vm = { path = "../tidal-vm" }

[[bin]]
name = "tidal"
path = "src/main.rs"
