[package]
name = "tidal-cli"
version = "0.1.10"
edition = "2024"

[dependencies]
tidal-parser = { path = "../tidal-parser" }
tidal-runtime = { path = "../tidal-runtime" }

[[bin]]
name = "tidal"
path = "src/main.rs"
